### ISSUE TITLE
aw-watcher-window reports wrong window with multiple app instances

### ISSUE THREAD

**Issue by tbuckler** [ActivityWatch/activitywatch#579]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- OSX 10.15.7 & 11.1 : 
- 0.10.0: 

I have not tried this in Windows yet.

## Describe the bug
When running multiple instance of the same app, AW timeline reports the frontmost window for the first app instance even when the second instance is the active application.

## To Reproduce

In my case I'm using a database development platform "4D" from 4d.com, but I have tried this with MS Word as well:

1. Find the app in applications, duplicate it. (Word.app for example)
2. Open one instance, create a document "Letter A" and save it, now the window has the title of "Letter A"
3. Open the second instance Word Copy.app, create a document "Letter B", now the window has the title "Letter B"
4. Open AW Timeline and note that there's no reference to "Letter B" and the the time spent on "Letter A" also includes the time you actually spent on the second letter in the second instance of Word.

[activitywatchLogs202103200846.zip](https://github.com/ActivityWatch/activitywatch/files/6175831/activitywatchLogs202103200846.zip)
## Expected behavior
Should be able to see the different window titles and compute the times spent in each.

## Documentation
Logs attached, using two instances of 4D. Fresh install of 4D with fresh install of AW on separate machine from which this issue was noticed.

## Additional context
Word might not be a practical example since you can have multiple docs open simultaneously, but is common enough to test with. Other apps do not allow multiple projects to be open at the same time. & replicating the app solves that problem.

**Comment by johan-bjareholt** [comment]
Hello, thanks for filing this issue. We were not aware that this issue existed before.

However, we are in the process of rewriting how the macOS support works as we have seen a few other problematic issues with it, hopefully that should solve the issue once that's done.

https://github.com/ActivityWatch/aw-watcher-window/pull/49

**Comment by tbuckler** [comment]
Hi There,

Sorry for coming back to this issue so far after bringing it up in March, but I'm on a new machine and new OS (MacOS Monterey) and this problem persists. AW v0.11.0. I can say the problem existed two os versions prior: Catalina. Not sure I used AW before that...

When I have two instances of the same app open, aw-watcher reports App:Unknown and Title:Unknown for the second instance. I recall, and based on the title of this thread, that earlier I was getting the _wrong_ title, now it's just "unknown" — see attached.

As soon as I quit the first instance, AW starts picking up the app and title properly for the second instance. Now that "becomes the first" and only instance, so if I again open another instance, it's that most recently opened instance that AW can't identify.

If I can help in any way, please advise,
Thx
Tom

/encl.


Tom Buckler | Buckler Microelectronics Inc.
17008 - 90 Avenue NW | Suite 272 | Edmonton | AB | Canada | T5T 1L6
Cell: (780) 499-5525
