### ISSUE TITLE
Unable to stop the stop watch

### ISSUE THREAD

**Issue by Colemak-cpu** [ActivityWatch/activitywatch#615]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 7
- **ActivityWatch version**: v0.11.0

## Describe the bug

When I try to use the Stopwatch after updating it shows some TypeError after reloading the page the stopwatch seems to be running but again when trying to stop it ,it shows the same error so I have to delete that to stop it going on
## To Reproduce
  Steps to reproduce the behavior, for example:
    1. Go to Stop Watch
    2. Create a new stopwatch
    3. TypeError: Cannot read property 'timestamp' of null. See dev console (F12) and/or server logs for more info,

 See this gif
![kh5Fk8](https://user-images.githubusercontent.com/77240155/122587395-680a6a80-d07b-11eb-81cf-7652a93558c9.gif)

## Expected behavior

It does start the stop watch but I cannot stop it without deleting. 
## Documentation

![image](https://user-images.githubusercontent.com/77240155/122587212-2da0cd80-d07b-11eb-86f8-014c2776c4de.png)
This is what appears after pressing F12 Key

**Comment by kelvinbward** [comment]
I too have been encountering this.

**Comment by wsdookadr** [comment]
Please fix this bug, it's an important feature that would be very useful

**Comment by MohammedNoureldin** [comment]
+1, I have the exact same problem. Is any hot-fix coming soon?

**Comment by ErikBjare** [comment]
A fix has been merged, but can't say when there will be a new release (I'm a bit busy, but hopefully soon).

If you're feeling adventurous, you can try a nightly build (see #507) in the meantime.

**Comment by MohammedNoureldin** [comment]
@ErikBjare unfortunately, in the nightly build it has not been fixed, I have just tried that and I still get the same issue.

**Comment by ErikBjare** [comment]
@MohammedNoureldin Ah yeah, sorry, I had not updated the webui submodule which contains the fix.

I just pushed a change with the updated submodule, so the next nightly build should have the issue resolved (just tested locally).

**Comment by TamerElsherif** [comment]
me too had the same error

**Comment by MohammedNoureldin** [comment]
Hi @ErikBjare, are you sure that this issue is fixed in the nightly build? I tried it but I still get the same issue.

**Comment by ErikBjare** [comment]
@MohammedNoureldin Sorry I was mistaken, it should finally be fixed in https://github.com/ActivityWatch/aw-webui/commit/7feadde52419ae5d4d1570a543421627f8158b1f

Next nightly will definitely contain it!

**Comment by MohammedNoureldin** [comment]
@ErikBjare unfortunately, still not working. In addition, the whole application in the nightly build for the last few days keeps freezing when I try to do anything or navigate.

**Comment by wsdookadr** [comment]
@ErikBjare I think you're making good progress towards fixing this. Perhaps if you wrote some tests to capture the targetted functionality, that could help.

**Comment by MohammedNoureldin** [comment]
That has not been fixed, why was this closed?

**Comment by MohammedNoureldin** [comment]
Thank you very much for merging, @ErikBjare! Can I somehow get the released v0.3 or should I wait for the nightly build? Because the version on the main page is v0.11

**Comment by MohammedNoureldin** [comment]
This seems to be working! Thanks a lot @ErikBjare! I just had the issue when opening the page in the browser that I could not navigate anywhere, but refreshing hard-refreshing the page solved the issue and now everything seems to be good!

**Comment by ErikBjare** [comment]
@MohammedNoureldin Awesome, happy to hear it!

Let us know if you find any new issues in the nightly!

**Comment by porelli** [comment]
I just downloaded the [build #195](https://github.com/ActivityWatch/activitywatch/actions/runs/1283324272) because I had the same problem reported here. Now when I click "Stop" I don't get any error and apparently the task stopped (UI shows it in the history and no errors in the web console) but if I refresh the page I can see that the stopwatch is still running.

The [build #190](https://github.com/ActivityWatch/activitywatch/actions/runs/1242036227) reported previously in this thread seems having the same problem.

(this project is amazing!)

**Comment by MohammedNoureldin** [comment]
Same here

**Comment by wsdookadr** [comment]
A test that covers the aforementioned would be useful

**Comment by porelli** [comment]
I confirm build #199 is working for me. Thanks @ErikBjare !

**Comment by wsdookadr** [comment]
I am still seeing this with build 19
![Screenshot from 2021-10-21 01-13-38](https://user-images.githubusercontent.com/180373/138179977-fca8eef2-8be1-42da-9cad-7b4f867e4e6d.png)
