### ISSUE TITLE
First launch of Activity on Web UI freezes it. 

### ISSUE THREAD

**Issue by JFMugen** [ActivityWatch/activitywatch#639]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **Win 10 - 21H1**: 
- **v0.11.0**: 

## Describe the bug
Every day, when I open the web UI and click "Activity" for the first time, it freezes for a minute. Reloading the page doesn't help. After a minute (I click Activity again), it starts working normally for the whole day. 

I don't leave my PC open at night, so I am not sure if that would create a difference or not. 

## To Reproduce
Right Click AW -> Open Dashboard
Click Activity

## Expected behavior
Open instantly, like second+ time. 

## Documentation
I am not sure if it is about my problem, but it was the weird one among other logs 
[aw-watcher-window_2021-06-27T15-06-42.log](https://github.com/ActivityWatch/activitywatch/files/6822753/aw-watcher-window_2021-06-27T15-06-42.log)

## Additional context
Tried to search with few different keywords but couldn't see anything about the issue. Hopefully its not duplicate.

**Comment by MartinNiederl** [comment]
Have the same problem. Been using it for about a month and a half and every time I open the dashboard for the first time I have to wait about half a minute before I can access any page, but after that everything works normally.

**Comment by ErikBjare** [comment]
@MartinNiederl Can you confirm that you are also using Windows?

Seems to be Windows-specific, weirdly enough.

**Comment by JFMugen** [comment]
> Can people test with different browsers and see if the behavior is the same?

I just test with Edge - Brave - Opera GX and Firefox. All have the issue (Edge was the worst for some reason.)

**Comment by JFMugen** [comment]
@ErikBjare Anything I can do in this page to help you identify the issue? 

![image](https://user-images.githubusercontent.com/61559703/160006549-f8cdccf2-dbdc-4dc3-a4f3-92180e8263e7.png)

**Comment by antoson** [comment]
I have the same issue. I am experiencing it for 9+ months.
Current system:
```
Windows 11 21H2 Build 22000.675
Firefox 100.0.2
```

**Comment by AlexW29ChemE** [comment]
My brother just started using activity watch and it also took 1.2 minutes before becoming responsive. He is using version 0.12.1 in Chrome and on Windows 10. 

The holdup appears to be the first request sent "localhost" which takes 1.2 minutes, following this all the javascript is loaded and page becomes reponsive. However the network tab is showing two "logo.png" requests taking 1.1 mins for server to respond and two "query/" requests failing after 30 seconds (see screen clips of network tab and console in chrome). Once cached further reloads have no issues.

![image](https://user-images.githubusercontent.com/103972325/204161991-bf08bb27-7c84-4941-b099-c58ca3b3f197.png)
![image](https://user-images.githubusercontent.com/103972325/204160898-f86d9920-3951-47e5-a659-6dc36ee47e17.png)

**Comment by itsab11** [comment]
Have the same issue. 
```
Win 11 21H22 (Build 22000.1455)
Browser: Microsoft Edge Version 109.0.1518.49
```

Can confirm it has been like that right from the start, so even with a completely fresh and empty database.

**Comment by ErikBjare** [comment]
It's fixed in the latest v0.12.2b1 release: https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.2b1

A proper v0.12.2 release will come as soon as people validate that the fix works without issues.

**Comment by GerroDen** [comment]
At the moment the tool is sadly unusable to me. Even with v0.13.2 (rust) I still have these issues and the loading takes half a minute if the browser does not crash before.

Version: v0.13.2 (rust)
OS: MacOS 15.3.2 (24D81)
Machine: Apple M1 Max

**Comment by BelKed** [comment]
Please share the server logs in order to help up diagnose the issue.

Click on the ActivityWatch logo in the system tray and then on Open logs folder.

**Comment by ErikBjare** [comment]
@GerroDen The log is practically empty, and given the filename, seems to be from 2023-05-20?

**Comment by ErikBjare** [comment]
This specific issue as originally reported was fixed.

If anyone else experiences similar issues, please open a new issue. (feel free to refer to this one if you think it's relevant)
